### PR TITLE
Doc tweaks

### PR DESCRIPTION
**Pull request by nextmat**
This is a general sweep of the current README based on knowing the areas where users tend to get stuck over the years. [Preview here](https://github.com/librato/librato-rails/blob/doc_tweaks/README.md).

The biggest change is moving the new suites documentation into the "Automatic Measurements" section & elaborating a bit more length on what people actually get when they hook up the gem. We've never really done a good job of describing what is supported and what specific metrics are, so this is an interim step towards making that better.

### CODE REVIEW

**Comment by jderrett** [comment]
Looks great to me!

**Comment by mbeale** [comment]
this is awesome

**Comment by bdehamer** [comment]
👍

**Pull request merged**
