### PR TITLE
move configuration inside config.before_configuration block

### PR DESCRIPTION
**Pull request by zacksiri**

### CODE REVIEW

**Comment by nextmat** [comment]
This makes sense to me, was the issue that `config` is no longer available outside of configuration blocks in 4.2.5.1?

**Comment by nextmat** [comment]
Nope that isn't it because you are calling `before_configuration` on it. Can you clarify what the specific issue was?

**Comment by zacksiri** [comment]
@nextmat  yeah the issue is if the configuration isn't loaded in the block I can't use Rails.application.secrets because the Application isn't initialized yet and therefore Rails.application is nil, that was the problem. when I put it in the config.before_comfiguration block I am sure that the application has already been initialized and the secrets have been loaded and I can use them in my yml file.

**Comment by nextmat** [comment]
@zacksiri In general I agree with what you said & I definitely think we want to support `Rails.application.secrets` as an option going forward. However that doesn't exist in Rails versions [prior to 4.1](http://edgeguides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml) and we support all the way back to Rails 3.0 (and have a large existing userbase).

How is using Rails secrets hash different from your perspective from using the librato.yml file? Both are yml and both allow ERB to let you embed values from other sources, including the filesystem or env vars (both are pretty common practice). Is there something special about the Rails secrets hash that makes it an improvement? My impression was it was mostly a way to introduce consistency in an area where lots of folks were handrolling.

If your point is that we should detect secrets from Rails hash instead of detecting our own config file or env vars, really what that would mean is just adding a third way to configure librato-rails for users of 4.1+. Is that what you are suggesting?

Thanks for your feedback and the PR!

**Comment by nextmat** [comment]
Related: https://github.com/librato/librato-rails/wiki/Configuration#combining-config-files-and-environment-variables

**Comment by zacksiri** [comment]
yes, the soul purpose is consistency's sake, I mean you could go down the route of detecting from the secret hash, that would make me have to not add a librato.yml file to my app. but you could keep it this way, too my solution shouldn't effect the people who want to use the config the old way, it just adds the ability for me to pull stuff from the secrets hash, as you can see the tests are passing for all the versions.

think about it for a sec, there are now 4 different ways to store and consume secrets depending on which infrastructure you use, etcd, consul, environment variables, kubernetes volume, zookeeper, depending on the solution you'd have to manually put code in place to consume the secrets, if moving forward we stick to supporting Rails secret, it no longer matters, people can be doing what they want to inject things into secrets, but now the entire app is using one consistent way to access all of that.

**Comment by nextmat** [comment]
Sounds good, thanks for the clarification. 

To summarize the issue here was that if you tried to interpolate values from the `Rails.application.secrets` hash in your `librato.yml` it wasn't available because the file hadn't been evaluated by Rails yet. Moving our prefconfiguration logic into a `config.before_configuration` block addresses this.

Thanks for the patch!

**Comment by nextmat** [comment]
Released in v1.2.0

**Pull request merged**
